// Copyright Octelium Labs, LLC. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: authv1.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MainService_AuthenticateWithAuthenticationToken_FullMethodName = "/octelium.api.main.auth.v1.MainService/AuthenticateWithAuthenticationToken"
	MainService_AuthenticateWithAssertion_FullMethodName           = "/octelium.api.main.auth.v1.MainService/AuthenticateWithAssertion"
	MainService_AuthenticateWithRefreshToken_FullMethodName        = "/octelium.api.main.auth.v1.MainService/AuthenticateWithRefreshToken"
	MainService_Logout_FullMethodName                              = "/octelium.api.main.auth.v1.MainService/Logout"
	MainService_RegisterDeviceBegin_FullMethodName                 = "/octelium.api.main.auth.v1.MainService/RegisterDeviceBegin"
	MainService_RegisterDeviceFinish_FullMethodName                = "/octelium.api.main.auth.v1.MainService/RegisterDeviceFinish"
)

// MainServiceClient is the client API for MainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MainServiceClient interface {
	AuthenticateWithAuthenticationToken(ctx context.Context, in *AuthenticateWithAuthenticationTokenRequest, opts ...grpc.CallOption) (*SessionToken, error)
	AuthenticateWithAssertion(ctx context.Context, in *AuthenticateWithAssertionRequest, opts ...grpc.CallOption) (*SessionToken, error)
	AuthenticateWithRefreshToken(ctx context.Context, in *AuthenticateWithRefreshTokenRequest, opts ...grpc.CallOption) (*SessionToken, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	RegisterDeviceBegin(ctx context.Context, in *RegisterDeviceBeginRequest, opts ...grpc.CallOption) (*RegisterDeviceBeginResponse, error)
	RegisterDeviceFinish(ctx context.Context, in *RegisterDeviceFinishRequest, opts ...grpc.CallOption) (*RegisterDeviceFinishResponse, error)
}

type mainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMainServiceClient(cc grpc.ClientConnInterface) MainServiceClient {
	return &mainServiceClient{cc}
}

func (c *mainServiceClient) AuthenticateWithAuthenticationToken(ctx context.Context, in *AuthenticateWithAuthenticationTokenRequest, opts ...grpc.CallOption) (*SessionToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, MainService_AuthenticateWithAuthenticationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) AuthenticateWithAssertion(ctx context.Context, in *AuthenticateWithAssertionRequest, opts ...grpc.CallOption) (*SessionToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, MainService_AuthenticateWithAssertion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) AuthenticateWithRefreshToken(ctx context.Context, in *AuthenticateWithRefreshTokenRequest, opts ...grpc.CallOption) (*SessionToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, MainService_AuthenticateWithRefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, MainService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) RegisterDeviceBegin(ctx context.Context, in *RegisterDeviceBeginRequest, opts ...grpc.CallOption) (*RegisterDeviceBeginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceBeginResponse)
	err := c.cc.Invoke(ctx, MainService_RegisterDeviceBegin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) RegisterDeviceFinish(ctx context.Context, in *RegisterDeviceFinishRequest, opts ...grpc.CallOption) (*RegisterDeviceFinishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceFinishResponse)
	err := c.cc.Invoke(ctx, MainService_RegisterDeviceFinish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MainServiceServer is the server API for MainService service.
// All implementations must embed UnimplementedMainServiceServer
// for forward compatibility.
type MainServiceServer interface {
	AuthenticateWithAuthenticationToken(context.Context, *AuthenticateWithAuthenticationTokenRequest) (*SessionToken, error)
	AuthenticateWithAssertion(context.Context, *AuthenticateWithAssertionRequest) (*SessionToken, error)
	AuthenticateWithRefreshToken(context.Context, *AuthenticateWithRefreshTokenRequest) (*SessionToken, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	RegisterDeviceBegin(context.Context, *RegisterDeviceBeginRequest) (*RegisterDeviceBeginResponse, error)
	RegisterDeviceFinish(context.Context, *RegisterDeviceFinishRequest) (*RegisterDeviceFinishResponse, error)
	mustEmbedUnimplementedMainServiceServer()
}

// UnimplementedMainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMainServiceServer struct{}

func (UnimplementedMainServiceServer) AuthenticateWithAuthenticationToken(context.Context, *AuthenticateWithAuthenticationTokenRequest) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateWithAuthenticationToken not implemented")
}
func (UnimplementedMainServiceServer) AuthenticateWithAssertion(context.Context, *AuthenticateWithAssertionRequest) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateWithAssertion not implemented")
}
func (UnimplementedMainServiceServer) AuthenticateWithRefreshToken(context.Context, *AuthenticateWithRefreshTokenRequest) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateWithRefreshToken not implemented")
}
func (UnimplementedMainServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedMainServiceServer) RegisterDeviceBegin(context.Context, *RegisterDeviceBeginRequest) (*RegisterDeviceBeginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDeviceBegin not implemented")
}
func (UnimplementedMainServiceServer) RegisterDeviceFinish(context.Context, *RegisterDeviceFinishRequest) (*RegisterDeviceFinishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDeviceFinish not implemented")
}
func (UnimplementedMainServiceServer) mustEmbedUnimplementedMainServiceServer() {}
func (UnimplementedMainServiceServer) testEmbeddedByValue()                     {}

// UnsafeMainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MainServiceServer will
// result in compilation errors.
type UnsafeMainServiceServer interface {
	mustEmbedUnimplementedMainServiceServer()
}

func RegisterMainServiceServer(s grpc.ServiceRegistrar, srv MainServiceServer) {
	// If the following call pancis, it indicates UnimplementedMainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MainService_ServiceDesc, srv)
}

func _MainService_AuthenticateWithAuthenticationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateWithAuthenticationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).AuthenticateWithAuthenticationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_AuthenticateWithAuthenticationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).AuthenticateWithAuthenticationToken(ctx, req.(*AuthenticateWithAuthenticationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_AuthenticateWithAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateWithAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).AuthenticateWithAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_AuthenticateWithAssertion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).AuthenticateWithAssertion(ctx, req.(*AuthenticateWithAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_AuthenticateWithRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateWithRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).AuthenticateWithRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_AuthenticateWithRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).AuthenticateWithRefreshToken(ctx, req.(*AuthenticateWithRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_RegisterDeviceBegin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceBeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).RegisterDeviceBegin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_RegisterDeviceBegin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).RegisterDeviceBegin(ctx, req.(*RegisterDeviceBeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_RegisterDeviceFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceFinishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).RegisterDeviceFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_RegisterDeviceFinish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).RegisterDeviceFinish(ctx, req.(*RegisterDeviceFinishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MainService_ServiceDesc is the grpc.ServiceDesc for MainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.main.auth.v1.MainService",
	HandlerType: (*MainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateWithAuthenticationToken",
			Handler:    _MainService_AuthenticateWithAuthenticationToken_Handler,
		},
		{
			MethodName: "AuthenticateWithAssertion",
			Handler:    _MainService_AuthenticateWithAssertion_Handler,
		},
		{
			MethodName: "AuthenticateWithRefreshToken",
			Handler:    _MainService_AuthenticateWithRefreshToken_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _MainService_Logout_Handler,
		},
		{
			MethodName: "RegisterDeviceBegin",
			Handler:    _MainService_RegisterDeviceBegin_Handler,
		},
		{
			MethodName: "RegisterDeviceFinish",
			Handler:    _MainService_RegisterDeviceFinish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authv1.proto",
}
