// Copyright Octelium Labs, LLC. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: mobilev1.proto

package mobilev1

import (
	context "context"
	daemonv1 "github.com/octelium/octelium/apis/client/daemonv1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MainService_GetInfo_FullMethodName                = "/octelium.api.client.mobile.v1.MainService/GetInfo"
	MainService_GetStatus_FullMethodName              = "/octelium.api.client.mobile.v1.MainService/GetStatus"
	MainService_Authenticate_FullMethodName           = "/octelium.api.client.mobile.v1.MainService/Authenticate"
	MainService_CompleteAuthentication_FullMethodName = "/octelium.api.client.mobile.v1.MainService/CompleteAuthentication"
	MainService_Connect_FullMethodName                = "/octelium.api.client.mobile.v1.MainService/Connect"
	MainService_Disconnect_FullMethodName             = "/octelium.api.client.mobile.v1.MainService/Disconnect"
	MainService_Logout_FullMethodName                 = "/octelium.api.client.mobile.v1.MainService/Logout"
	MainService_DeleteDomain_FullMethodName           = "/octelium.api.client.mobile.v1.MainService/DeleteDomain"
	MainService_GetOperation_FullMethodName           = "/octelium.api.client.mobile.v1.MainService/GetOperation"
	MainService_CancelOperation_FullMethodName        = "/octelium.api.client.mobile.v1.MainService/CancelOperation"
	MainService_GetAPICredential_FullMethodName       = "/octelium.api.client.mobile.v1.MainService/GetAPICredential"
	MainService_UpdateDomainSettings_FullMethodName   = "/octelium.api.client.mobile.v1.MainService/UpdateDomainSettings"
	MainService_SetNetworkState_FullMethodName        = "/octelium.api.client.mobile.v1.MainService/SetNetworkState"
)

// MainServiceClient is the client API for MainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MainService is the API of liboctelium, the Octelium client library embedded
// by the Octelium Android and iOS applications.
//
// The Service is never served over the network. It is invoked in-process by
// the native layer of the application (i.e. the host) via the C ABI of
// liboctelium where a method is identified by its name (e.g. `Connect`) and
// both its request and its response are serialized protobuf messages. A
// failed call returns a gRPC status code along with a human-readable message.
//
// The buffers passed by the host remain owned by the host while the output
// buffers are allocated by liboctelium and they must be released via
// `octelium_free`. The Event and PlatformRequest callbacks can be invoked from
// arbitrary threads and their buffers are only valid during the callback. The
// host must never call `octelium_client_free` from within a callback. No
// callback is invoked once `octelium_client_free` returns.
//
// The Service intentionally reuses the local state model of the Octelium
// daemon API (i.e. octelium.api.client.daemon.v1) so that the mobile and the
// desktop applications share the same semantics of the domains, the
// Operations, the settings and the errors. However, the host itself owns the
// OS VPN lifecycle (i.e. VpnService on Android and NEPacketTunnelProvider on
// iOS). liboctelium asks the host to apply the tunnel configuration via
// PlatformRequest and it reports its state via Event.
//
// A liboctelium instance supports at most one connected domain at a time since
// the mobile OSes provide a single VPN interface per application. The
// ConnectionOptions fields that are not supported by the mobile clients (i.e.
// the KERNEL and GVISOR implementation modes, the served and published
// Services, the embedded SSH and SOCKS5 servers and the local DNS server) are
// rejected with INVALID_ARGUMENT. The autoConnect setting is persisted but
// acting upon it is the responsibility of the host (e.g. via the Android
// always-on VPN or the iOS on-demand rules).
type MainServiceClient interface {
	// GetInfo retrieves information about liboctelium and about the version of
	// this API it implements.
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// GetStatus retrieves a complete snapshot of the local Octelium state. The
	// same snapshot is also pushed via Event whenever the state changes.
	GetStatus(ctx context.Context, in *daemonv1.GetStatusRequest, opts ...grpc.CallOption) (*daemonv1.GetStatusResponse, error)
	// Authenticate starts authenticating to a Cluster.
	//
	// In the browser mode, the returned Operation is WAITING_FOR_USER and its
	// Action contains the Portal login URL. The host opens it via the system
	// authentication session (i.e. ASWebAuthenticationSession on iOS and Custom
	// Tabs on Android) and it passes the URL received at
	// GetInfoResponse.authenticationCallbackURL to CompleteAuthentication.
	Authenticate(ctx context.Context, in *daemonv1.AuthenticateRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error)
	// CompleteAuthentication completes a browser AUTHENTICATE Operation that is
	// WAITING_FOR_USER using the callback URL received by the host. An invalid
	// callback URL returns INVALID_ARGUMENT and it leaves the Operation waiting.
	CompleteAuthentication(ctx context.Context, in *CompleteAuthenticationRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error)
	// Connect starts connecting to a Cluster. liboctelium asks the host to
	// establish the tunnel via PlatformRequest.ApplyTunnelConfiguration.
	Connect(ctx context.Context, in *daemonv1.ConnectRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error)
	// Disconnect starts disconnecting from a Cluster. The host tears down the
	// tunnel once the Connection of the domain becomes DISCONNECTED.
	Disconnect(ctx context.Context, in *daemonv1.DisconnectRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error)
	Logout(ctx context.Context, in *daemonv1.LogoutRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error)
	DeleteDomain(ctx context.Context, in *daemonv1.DeleteDomainRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error)
	GetOperation(ctx context.Context, in *daemonv1.GetOperationRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error)
	CancelOperation(ctx context.Context, in *daemonv1.CancelOperationRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error)
	// GetAPICredential retrieves the current short-lived Cluster API access
	// token of a domain. The refresh token is never exposed. The host is
	// supposed to keep the access token in memory within its native layer.
	GetAPICredential(ctx context.Context, in *daemonv1.GetAPICredentialRequest, opts ...grpc.CallOption) (*daemonv1.GetAPICredentialResponse, error)
	UpdateDomainSettings(ctx context.Context, in *daemonv1.UpdateDomainSettingsRequest, opts ...grpc.CallOption) (*daemonv1.DomainSettings, error)
	// SetNetworkState informs liboctelium of the state of the underlying
	// network as observed by the host (i.e. ConnectivityManager on Android and
	// NWPathMonitor on iOS). liboctelium suspends reconnecting while no network
	// is available and it rebinds the tunnel transport whenever the underlying
	// network changes.
	SetNetworkState(ctx context.Context, in *SetNetworkStateRequest, opts ...grpc.CallOption) (*SetNetworkStateResponse, error)
}

type mainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMainServiceClient(cc grpc.ClientConnInterface) MainServiceClient {
	return &mainServiceClient{cc}
}

func (c *mainServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, MainService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetStatus(ctx context.Context, in *daemonv1.GetStatusRequest, opts ...grpc.CallOption) (*daemonv1.GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(daemonv1.GetStatusResponse)
	err := c.cc.Invoke(ctx, MainService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) Authenticate(ctx context.Context, in *daemonv1.AuthenticateRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(daemonv1.Operation)
	err := c.cc.Invoke(ctx, MainService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) CompleteAuthentication(ctx context.Context, in *CompleteAuthenticationRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(daemonv1.Operation)
	err := c.cc.Invoke(ctx, MainService_CompleteAuthentication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) Connect(ctx context.Context, in *daemonv1.ConnectRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(daemonv1.Operation)
	err := c.cc.Invoke(ctx, MainService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) Disconnect(ctx context.Context, in *daemonv1.DisconnectRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(daemonv1.Operation)
	err := c.cc.Invoke(ctx, MainService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) Logout(ctx context.Context, in *daemonv1.LogoutRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(daemonv1.Operation)
	err := c.cc.Invoke(ctx, MainService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) DeleteDomain(ctx context.Context, in *daemonv1.DeleteDomainRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(daemonv1.Operation)
	err := c.cc.Invoke(ctx, MainService_DeleteDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetOperation(ctx context.Context, in *daemonv1.GetOperationRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(daemonv1.Operation)
	err := c.cc.Invoke(ctx, MainService_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) CancelOperation(ctx context.Context, in *daemonv1.CancelOperationRequest, opts ...grpc.CallOption) (*daemonv1.Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(daemonv1.Operation)
	err := c.cc.Invoke(ctx, MainService_CancelOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetAPICredential(ctx context.Context, in *daemonv1.GetAPICredentialRequest, opts ...grpc.CallOption) (*daemonv1.GetAPICredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(daemonv1.GetAPICredentialResponse)
	err := c.cc.Invoke(ctx, MainService_GetAPICredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateDomainSettings(ctx context.Context, in *daemonv1.UpdateDomainSettingsRequest, opts ...grpc.CallOption) (*daemonv1.DomainSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(daemonv1.DomainSettings)
	err := c.cc.Invoke(ctx, MainService_UpdateDomainSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) SetNetworkState(ctx context.Context, in *SetNetworkStateRequest, opts ...grpc.CallOption) (*SetNetworkStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNetworkStateResponse)
	err := c.cc.Invoke(ctx, MainService_SetNetworkState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MainServiceServer is the server API for MainService service.
// All implementations must embed UnimplementedMainServiceServer
// for forward compatibility.
//
// MainService is the API of liboctelium, the Octelium client library embedded
// by the Octelium Android and iOS applications.
//
// The Service is never served over the network. It is invoked in-process by
// the native layer of the application (i.e. the host) via the C ABI of
// liboctelium where a method is identified by its name (e.g. `Connect`) and
// both its request and its response are serialized protobuf messages. A
// failed call returns a gRPC status code along with a human-readable message.
//
// The buffers passed by the host remain owned by the host while the output
// buffers are allocated by liboctelium and they must be released via
// `octelium_free`. The Event and PlatformRequest callbacks can be invoked from
// arbitrary threads and their buffers are only valid during the callback. The
// host must never call `octelium_client_free` from within a callback. No
// callback is invoked once `octelium_client_free` returns.
//
// The Service intentionally reuses the local state model of the Octelium
// daemon API (i.e. octelium.api.client.daemon.v1) so that the mobile and the
// desktop applications share the same semantics of the domains, the
// Operations, the settings and the errors. However, the host itself owns the
// OS VPN lifecycle (i.e. VpnService on Android and NEPacketTunnelProvider on
// iOS). liboctelium asks the host to apply the tunnel configuration via
// PlatformRequest and it reports its state via Event.
//
// A liboctelium instance supports at most one connected domain at a time since
// the mobile OSes provide a single VPN interface per application. The
// ConnectionOptions fields that are not supported by the mobile clients (i.e.
// the KERNEL and GVISOR implementation modes, the served and published
// Services, the embedded SSH and SOCKS5 servers and the local DNS server) are
// rejected with INVALID_ARGUMENT. The autoConnect setting is persisted but
// acting upon it is the responsibility of the host (e.g. via the Android
// always-on VPN or the iOS on-demand rules).
type MainServiceServer interface {
	// GetInfo retrieves information about liboctelium and about the version of
	// this API it implements.
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// GetStatus retrieves a complete snapshot of the local Octelium state. The
	// same snapshot is also pushed via Event whenever the state changes.
	GetStatus(context.Context, *daemonv1.GetStatusRequest) (*daemonv1.GetStatusResponse, error)
	// Authenticate starts authenticating to a Cluster.
	//
	// In the browser mode, the returned Operation is WAITING_FOR_USER and its
	// Action contains the Portal login URL. The host opens it via the system
	// authentication session (i.e. ASWebAuthenticationSession on iOS and Custom
	// Tabs on Android) and it passes the URL received at
	// GetInfoResponse.authenticationCallbackURL to CompleteAuthentication.
	Authenticate(context.Context, *daemonv1.AuthenticateRequest) (*daemonv1.Operation, error)
	// CompleteAuthentication completes a browser AUTHENTICATE Operation that is
	// WAITING_FOR_USER using the callback URL received by the host. An invalid
	// callback URL returns INVALID_ARGUMENT and it leaves the Operation waiting.
	CompleteAuthentication(context.Context, *CompleteAuthenticationRequest) (*daemonv1.Operation, error)
	// Connect starts connecting to a Cluster. liboctelium asks the host to
	// establish the tunnel via PlatformRequest.ApplyTunnelConfiguration.
	Connect(context.Context, *daemonv1.ConnectRequest) (*daemonv1.Operation, error)
	// Disconnect starts disconnecting from a Cluster. The host tears down the
	// tunnel once the Connection of the domain becomes DISCONNECTED.
	Disconnect(context.Context, *daemonv1.DisconnectRequest) (*daemonv1.Operation, error)
	Logout(context.Context, *daemonv1.LogoutRequest) (*daemonv1.Operation, error)
	DeleteDomain(context.Context, *daemonv1.DeleteDomainRequest) (*daemonv1.Operation, error)
	GetOperation(context.Context, *daemonv1.GetOperationRequest) (*daemonv1.Operation, error)
	CancelOperation(context.Context, *daemonv1.CancelOperationRequest) (*daemonv1.Operation, error)
	// GetAPICredential retrieves the current short-lived Cluster API access
	// token of a domain. The refresh token is never exposed. The host is
	// supposed to keep the access token in memory within its native layer.
	GetAPICredential(context.Context, *daemonv1.GetAPICredentialRequest) (*daemonv1.GetAPICredentialResponse, error)
	UpdateDomainSettings(context.Context, *daemonv1.UpdateDomainSettingsRequest) (*daemonv1.DomainSettings, error)
	// SetNetworkState informs liboctelium of the state of the underlying
	// network as observed by the host (i.e. ConnectivityManager on Android and
	// NWPathMonitor on iOS). liboctelium suspends reconnecting while no network
	// is available and it rebinds the tunnel transport whenever the underlying
	// network changes.
	SetNetworkState(context.Context, *SetNetworkStateRequest) (*SetNetworkStateResponse, error)
	mustEmbedUnimplementedMainServiceServer()
}

// UnimplementedMainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMainServiceServer struct{}

func (UnimplementedMainServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedMainServiceServer) GetStatus(context.Context, *daemonv1.GetStatusRequest) (*daemonv1.GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedMainServiceServer) Authenticate(context.Context, *daemonv1.AuthenticateRequest) (*daemonv1.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedMainServiceServer) CompleteAuthentication(context.Context, *CompleteAuthenticationRequest) (*daemonv1.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteAuthentication not implemented")
}
func (UnimplementedMainServiceServer) Connect(context.Context, *daemonv1.ConnectRequest) (*daemonv1.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedMainServiceServer) Disconnect(context.Context, *daemonv1.DisconnectRequest) (*daemonv1.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedMainServiceServer) Logout(context.Context, *daemonv1.LogoutRequest) (*daemonv1.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedMainServiceServer) DeleteDomain(context.Context, *daemonv1.DeleteDomainRequest) (*daemonv1.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDomain not implemented")
}
func (UnimplementedMainServiceServer) GetOperation(context.Context, *daemonv1.GetOperationRequest) (*daemonv1.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedMainServiceServer) CancelOperation(context.Context, *daemonv1.CancelOperationRequest) (*daemonv1.Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOperation not implemented")
}
func (UnimplementedMainServiceServer) GetAPICredential(context.Context, *daemonv1.GetAPICredentialRequest) (*daemonv1.GetAPICredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAPICredential not implemented")
}
func (UnimplementedMainServiceServer) UpdateDomainSettings(context.Context, *daemonv1.UpdateDomainSettingsRequest) (*daemonv1.DomainSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDomainSettings not implemented")
}
func (UnimplementedMainServiceServer) SetNetworkState(context.Context, *SetNetworkStateRequest) (*SetNetworkStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNetworkState not implemented")
}
func (UnimplementedMainServiceServer) mustEmbedUnimplementedMainServiceServer() {}
func (UnimplementedMainServiceServer) testEmbeddedByValue()                     {}

// UnsafeMainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MainServiceServer will
// result in compilation errors.
type UnsafeMainServiceServer interface {
	mustEmbedUnimplementedMainServiceServer()
}

func RegisterMainServiceServer(s grpc.ServiceRegistrar, srv MainServiceServer) {
	// If the following call pancis, it indicates UnimplementedMainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MainService_ServiceDesc, srv)
}

func _MainService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(daemonv1.GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetStatus(ctx, req.(*daemonv1.GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(daemonv1.AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).Authenticate(ctx, req.(*daemonv1.AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_CompleteAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteAuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).CompleteAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_CompleteAuthentication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).CompleteAuthentication(ctx, req.(*CompleteAuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(daemonv1.ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).Connect(ctx, req.(*daemonv1.ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(daemonv1.DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).Disconnect(ctx, req.(*daemonv1.DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(daemonv1.LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).Logout(ctx, req.(*daemonv1.LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_DeleteDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(daemonv1.DeleteDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).DeleteDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_DeleteDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).DeleteDomain(ctx, req.(*daemonv1.DeleteDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(daemonv1.GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetOperation(ctx, req.(*daemonv1.GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_CancelOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(daemonv1.CancelOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).CancelOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_CancelOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).CancelOperation(ctx, req.(*daemonv1.CancelOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetAPICredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(daemonv1.GetAPICredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetAPICredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetAPICredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetAPICredential(ctx, req.(*daemonv1.GetAPICredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateDomainSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(daemonv1.UpdateDomainSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateDomainSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateDomainSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateDomainSettings(ctx, req.(*daemonv1.UpdateDomainSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_SetNetworkState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNetworkStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).SetNetworkState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_SetNetworkState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).SetNetworkState(ctx, req.(*SetNetworkStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MainService_ServiceDesc is the grpc.ServiceDesc for MainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.client.mobile.v1.MainService",
	HandlerType: (*MainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _MainService_GetInfo_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _MainService_GetStatus_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _MainService_Authenticate_Handler,
		},
		{
			MethodName: "CompleteAuthentication",
			Handler:    _MainService_CompleteAuthentication_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _MainService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _MainService_Disconnect_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _MainService_Logout_Handler,
		},
		{
			MethodName: "DeleteDomain",
			Handler:    _MainService_DeleteDomain_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _MainService_GetOperation_Handler,
		},
		{
			MethodName: "CancelOperation",
			Handler:    _MainService_CancelOperation_Handler,
		},
		{
			MethodName: "GetAPICredential",
			Handler:    _MainService_GetAPICredential_Handler,
		},
		{
			MethodName: "UpdateDomainSettings",
			Handler:    _MainService_UpdateDomainSettings_Handler,
		},
		{
			MethodName: "SetNetworkState",
			Handler:    _MainService_SetNetworkState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mobilev1.proto",
}
