// Copyright Octelium Labs, LLC. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.21.12
// source: cvigilv1.proto

package cvigilv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheHTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Headers       []*CacheHTTP_Header    `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheHTTP) Reset() {
	*x = CacheHTTP{}
	mi := &file_cvigilv1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheHTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheHTTP) ProtoMessage() {}

func (x *CacheHTTP) ProtoReflect() protoreflect.Message {
	mi := &file_cvigilv1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheHTTP.ProtoReflect.Descriptor instead.
func (*CacheHTTP) Descriptor() ([]byte, []int) {
	return file_cvigilv1_proto_rawDescGZIP(), []int{0}
}

func (x *CacheHTTP) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CacheHTTP) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CacheHTTP) GetHeaders() []*CacheHTTP_Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

type CacheHTTP_Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheHTTP_Header) Reset() {
	*x = CacheHTTP_Header{}
	mi := &file_cvigilv1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheHTTP_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheHTTP_Header) ProtoMessage() {}

func (x *CacheHTTP_Header) ProtoReflect() protoreflect.Message {
	mi := &file_cvigilv1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheHTTP_Header.ProtoReflect.Descriptor instead.
func (*CacheHTTP_Header) Descriptor() ([]byte, []int) {
	return file_cvigilv1_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CacheHTTP_Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CacheHTTP_Header) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_cvigilv1_proto protoreflect.FileDescriptor

var file_cvigilv1_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x76, 0x69, 0x67, 0x69, 0x6c, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1d, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x69, 0x67, 0x69, 0x6c, 0x2e, 0x76, 0x31, 0x22,
	0xb2, 0x01, 0x0a, 0x09, 0x43, 0x61, 0x63, 0x68, 0x65, 0x48, 0x54, 0x54, 0x50, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x49, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75,
	0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x69,
	0x67, 0x69, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x48, 0x54, 0x54, 0x50,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x1a, 0x32, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2f, 0x6f, 0x63, 0x74, 0x65,
	0x6c, 0x69, 0x75, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x2f, 0x63, 0x76, 0x69, 0x67, 0x69, 0x6c, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_cvigilv1_proto_rawDescOnce sync.Once
	file_cvigilv1_proto_rawDescData = file_cvigilv1_proto_rawDesc
)

func file_cvigilv1_proto_rawDescGZIP() []byte {
	file_cvigilv1_proto_rawDescOnce.Do(func() {
		file_cvigilv1_proto_rawDescData = protoimpl.X.CompressGZIP(file_cvigilv1_proto_rawDescData)
	})
	return file_cvigilv1_proto_rawDescData
}

var file_cvigilv1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cvigilv1_proto_goTypes = []any{
	(*CacheHTTP)(nil),        // 0: octelium.api.cluster.vigil.v1.CacheHTTP
	(*CacheHTTP_Header)(nil), // 1: octelium.api.cluster.vigil.v1.CacheHTTP.Header
}
var file_cvigilv1_proto_depIdxs = []int32{
	1, // 0: octelium.api.cluster.vigil.v1.CacheHTTP.headers:type_name -> octelium.api.cluster.vigil.v1.CacheHTTP.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cvigilv1_proto_init() }
func file_cvigilv1_proto_init() {
	if File_cvigilv1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cvigilv1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cvigilv1_proto_goTypes,
		DependencyIndexes: file_cvigilv1_proto_depIdxs,
		MessageInfos:      file_cvigilv1_proto_msgTypes,
	}.Build()
	File_cvigilv1_proto = out.File
	file_cvigilv1_proto_rawDesc = nil
	file_cvigilv1_proto_goTypes = nil
	file_cvigilv1_proto_depIdxs = nil
}
