// Copyright Octelium Labs, LLC. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: daemonv1.proto

package daemonv1

import (
	context "context"
	metav1 "github.com/octelium/octelium/apis/main/metav1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MainService_GetInfo_FullMethodName              = "/octelium.api.client.daemon.v1.MainService/GetInfo"
	MainService_GetStatus_FullMethodName            = "/octelium.api.client.daemon.v1.MainService/GetStatus"
	MainService_WatchStatus_FullMethodName          = "/octelium.api.client.daemon.v1.MainService/WatchStatus"
	MainService_Authenticate_FullMethodName         = "/octelium.api.client.daemon.v1.MainService/Authenticate"
	MainService_Connect_FullMethodName              = "/octelium.api.client.daemon.v1.MainService/Connect"
	MainService_Disconnect_FullMethodName           = "/octelium.api.client.daemon.v1.MainService/Disconnect"
	MainService_Logout_FullMethodName               = "/octelium.api.client.daemon.v1.MainService/Logout"
	MainService_GetOperation_FullMethodName         = "/octelium.api.client.daemon.v1.MainService/GetOperation"
	MainService_CancelOperation_FullMethodName      = "/octelium.api.client.daemon.v1.MainService/CancelOperation"
	MainService_GetAPICredential_FullMethodName     = "/octelium.api.client.daemon.v1.MainService/GetAPICredential"
	MainService_UpdateDomainSettings_FullMethodName = "/octelium.api.client.daemon.v1.MainService/UpdateDomainSettings"
	MainService_DeleteDomain_FullMethodName         = "/octelium.api.client.daemon.v1.MainService/DeleteDomain"
)

// MainServiceClient is the client API for MainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MainService is the local Octelium client daemon API.
//
// The Service is implemented by the privileged Octelium daemon (i.e.
// `octelium daemon`) running on the client host and it is consumed by local
// unprivileged frontends such as the Octelium CLI itself and the Octelium
// desktop application.
//
// The Service is intentionally NOT a proxy to the Octelium Cluster API.
// Operations that merely read or modify Cluster resources (e.g. ListService,
// ListNamespace, GetStatus) are directly served by the Cluster API. This
// Service is limited to the operations whose state and effects belong to the
// local host (i.e. authentication, credential storage, Connection lifecycle,
// local networking and the locally persisted per-domain preferences).
//
// The transport is local-only. Unix domain sockets are used on Linux and macOS
// while named pipes are used on Windows. The daemon derives the identity of
// the calling OS principal from the IPC transport itself. Caller identity is
// never read from protobuf fields or from gRPC metadata. All the state that is
// visible via this Service is scoped to the calling OS principal.
//
// A Cluster domain becomes known to the daemon either via Authenticate or via
// UpdateDomainSettings. The methods that operate on a domain return NOT_FOUND
// for an unknown domain.
type MainServiceClient interface {
	// GetInfo retrieves information about the running Octelium daemon and about
	// the version of this API it implements.
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// GetStatus retrieves a complete snapshot of the local Octelium state that
	// belongs to the calling OS principal.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// WatchStatus watches the local Octelium state.
	//
	// The daemon sends the complete current state immediately once the stream is
	// established and it sends another complete state whenever the state
	// changes. In other words, the messages are snapshots and they are not
	// incremental events. A frontend that loses the stream simply re-subscribes
	// and rebuilds its entire state out of the first received message.
	WatchStatus(ctx context.Context, in *WatchStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetStatusResponse], error)
	// Authenticate starts authenticating the calling OS principal to a Cluster.
	//
	// Authentication is asynchronous. In the browser mode, the daemon generates
	// the PKCE code verifier, binds the loopback callback listener and builds
	// the Portal login URL before returning an Operation whose Action contains
	// the URL that the frontend is supposed to open using the interactive user's
	// system browser. The daemon itself never opens a browser since it runs as
	// root/SYSTEM and possibly in a non-interactive session.
	//
	// The daemon receives the browser callback at its own loopback listener,
	// redeems the authentication token, carries out the post-authentication
	// steps (e.g. Device registration) and stores the resulting credentials.
	//
	// At most one lifecycle Operation can be active for the same domain and OS
	// principal at a time. Otherwise, the RPC returns FAILED_PRECONDITION.
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*Operation, error)
	// Connect starts connecting the host to a Cluster.
	//
	// The RPC returns as soon as the Operation is accepted. The progress of the
	// Connection is observed via WatchStatus or GetOperation.
	//
	// Multiple domains can be connected concurrently. However, there is at most
	// one Connection per domain.
	//
	// If options is unset, the daemon uses the persisted DomainSettings of the
	// domain and falls back to its own defaults for whatever is unset. If
	// options is set, it applies to this Connection only and it is not
	// persisted.
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*Operation, error)
	// Disconnect starts disconnecting the host from a Cluster. Disconnecting an
	// already disconnected domain succeeds while disconnecting an unknown domain
	// returns NOT_FOUND.
	//
	// While a Connect Operation has not established the Connection yet, the
	// Connection is aborted via CancelOperation as opposed to Disconnect since
	// there can only be one active Operation per domain.
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*Operation, error)
	// Logout logs the calling OS principal out of a Cluster.
	//
	// Logout disconnects the domain if needed, invalidates the Cluster Session
	// whenever possible and removes the locally stored credentials. The
	// persisted DomainSettings of the domain are not removed. Use DeleteDomain
	// in order to remove the domain entirely.
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*Operation, error)
	// GetOperation retrieves an Operation by its ID.
	//
	// An Operation is only visible to the OS principal that owns it. Completed
	// Operations are retained for a bounded implementation-defined period after
	// which the RPC returns NOT_FOUND.
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	// CancelOperation requests the cancellation of an Operation. Cancellation is
	// cooperative. A successful RPC does not mean that the Operation has already
	// reached the CANCELED state by the time the response is returned.
	CancelOperation(ctx context.Context, in *CancelOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	// GetAPICredential retrieves the current short-lived Cluster API access
	// credential of a domain so that a local frontend can natively access the
	// Cluster API on its own.
	//
	// Refresh tokens and any other persistent credentials are never exposed via
	// this API. The accessToken is meant to be kept in the memory of the calling
	// process and it must never be persisted by the caller.
	//
	// The daemon transparently renews the access token as long as renewing it
	// does not require the interaction of the user. If no usable credential can
	// be obtained without such an interaction, the RPC returns UNAUTHENTICATED
	// and the caller is supposed to start or to watch an Authenticate Operation
	// instead.
	GetAPICredential(ctx context.Context, in *GetAPICredentialRequest, opts ...grpc.CallOption) (*GetAPICredentialResponse, error)
	// UpdateDomainSettings replaces the persisted local settings of a domain.
	//
	// Updating the settings does not reconfigure an already active Connection.
	// The new settings are used by the subsequent Connect Operations.
	UpdateDomainSettings(ctx context.Context, in *UpdateDomainSettingsRequest, opts ...grpc.CallOption) (*DomainSettings, error)
	// DeleteDomain removes a domain entirely. The domain is disconnected and
	// logged out if needed and both its credentials and its persisted
	// DomainSettings are removed.
	DeleteDomain(ctx context.Context, in *DeleteDomainRequest, opts ...grpc.CallOption) (*metav1.OperationResult, error)
}

type mainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMainServiceClient(cc grpc.ClientConnInterface) MainServiceClient {
	return &mainServiceClient{cc}
}

func (c *mainServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, MainService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, MainService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) WatchStatus(ctx context.Context, in *WatchStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetStatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MainService_ServiceDesc.Streams[0], MainService_WatchStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchStatusRequest, GetStatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MainService_WatchStatusClient = grpc.ServerStreamingClient[GetStatusResponse]

func (c *mainServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, MainService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, MainService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, MainService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, MainService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, MainService_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) CancelOperation(ctx context.Context, in *CancelOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, MainService_CancelOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetAPICredential(ctx context.Context, in *GetAPICredentialRequest, opts ...grpc.CallOption) (*GetAPICredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAPICredentialResponse)
	err := c.cc.Invoke(ctx, MainService_GetAPICredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateDomainSettings(ctx context.Context, in *UpdateDomainSettingsRequest, opts ...grpc.CallOption) (*DomainSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainSettings)
	err := c.cc.Invoke(ctx, MainService_UpdateDomainSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) DeleteDomain(ctx context.Context, in *DeleteDomainRequest, opts ...grpc.CallOption) (*metav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(metav1.OperationResult)
	err := c.cc.Invoke(ctx, MainService_DeleteDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MainServiceServer is the server API for MainService service.
// All implementations must embed UnimplementedMainServiceServer
// for forward compatibility.
//
// MainService is the local Octelium client daemon API.
//
// The Service is implemented by the privileged Octelium daemon (i.e.
// `octelium daemon`) running on the client host and it is consumed by local
// unprivileged frontends such as the Octelium CLI itself and the Octelium
// desktop application.
//
// The Service is intentionally NOT a proxy to the Octelium Cluster API.
// Operations that merely read or modify Cluster resources (e.g. ListService,
// ListNamespace, GetStatus) are directly served by the Cluster API. This
// Service is limited to the operations whose state and effects belong to the
// local host (i.e. authentication, credential storage, Connection lifecycle,
// local networking and the locally persisted per-domain preferences).
//
// The transport is local-only. Unix domain sockets are used on Linux and macOS
// while named pipes are used on Windows. The daemon derives the identity of
// the calling OS principal from the IPC transport itself. Caller identity is
// never read from protobuf fields or from gRPC metadata. All the state that is
// visible via this Service is scoped to the calling OS principal.
//
// A Cluster domain becomes known to the daemon either via Authenticate or via
// UpdateDomainSettings. The methods that operate on a domain return NOT_FOUND
// for an unknown domain.
type MainServiceServer interface {
	// GetInfo retrieves information about the running Octelium daemon and about
	// the version of this API it implements.
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// GetStatus retrieves a complete snapshot of the local Octelium state that
	// belongs to the calling OS principal.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// WatchStatus watches the local Octelium state.
	//
	// The daemon sends the complete current state immediately once the stream is
	// established and it sends another complete state whenever the state
	// changes. In other words, the messages are snapshots and they are not
	// incremental events. A frontend that loses the stream simply re-subscribes
	// and rebuilds its entire state out of the first received message.
	WatchStatus(*WatchStatusRequest, grpc.ServerStreamingServer[GetStatusResponse]) error
	// Authenticate starts authenticating the calling OS principal to a Cluster.
	//
	// Authentication is asynchronous. In the browser mode, the daemon generates
	// the PKCE code verifier, binds the loopback callback listener and builds
	// the Portal login URL before returning an Operation whose Action contains
	// the URL that the frontend is supposed to open using the interactive user's
	// system browser. The daemon itself never opens a browser since it runs as
	// root/SYSTEM and possibly in a non-interactive session.
	//
	// The daemon receives the browser callback at its own loopback listener,
	// redeems the authentication token, carries out the post-authentication
	// steps (e.g. Device registration) and stores the resulting credentials.
	//
	// At most one lifecycle Operation can be active for the same domain and OS
	// principal at a time. Otherwise, the RPC returns FAILED_PRECONDITION.
	Authenticate(context.Context, *AuthenticateRequest) (*Operation, error)
	// Connect starts connecting the host to a Cluster.
	//
	// The RPC returns as soon as the Operation is accepted. The progress of the
	// Connection is observed via WatchStatus or GetOperation.
	//
	// Multiple domains can be connected concurrently. However, there is at most
	// one Connection per domain.
	//
	// If options is unset, the daemon uses the persisted DomainSettings of the
	// domain and falls back to its own defaults for whatever is unset. If
	// options is set, it applies to this Connection only and it is not
	// persisted.
	Connect(context.Context, *ConnectRequest) (*Operation, error)
	// Disconnect starts disconnecting the host from a Cluster. Disconnecting an
	// already disconnected domain succeeds while disconnecting an unknown domain
	// returns NOT_FOUND.
	//
	// While a Connect Operation has not established the Connection yet, the
	// Connection is aborted via CancelOperation as opposed to Disconnect since
	// there can only be one active Operation per domain.
	Disconnect(context.Context, *DisconnectRequest) (*Operation, error)
	// Logout logs the calling OS principal out of a Cluster.
	//
	// Logout disconnects the domain if needed, invalidates the Cluster Session
	// whenever possible and removes the locally stored credentials. The
	// persisted DomainSettings of the domain are not removed. Use DeleteDomain
	// in order to remove the domain entirely.
	Logout(context.Context, *LogoutRequest) (*Operation, error)
	// GetOperation retrieves an Operation by its ID.
	//
	// An Operation is only visible to the OS principal that owns it. Completed
	// Operations are retained for a bounded implementation-defined period after
	// which the RPC returns NOT_FOUND.
	GetOperation(context.Context, *GetOperationRequest) (*Operation, error)
	// CancelOperation requests the cancellation of an Operation. Cancellation is
	// cooperative. A successful RPC does not mean that the Operation has already
	// reached the CANCELED state by the time the response is returned.
	CancelOperation(context.Context, *CancelOperationRequest) (*Operation, error)
	// GetAPICredential retrieves the current short-lived Cluster API access
	// credential of a domain so that a local frontend can natively access the
	// Cluster API on its own.
	//
	// Refresh tokens and any other persistent credentials are never exposed via
	// this API. The accessToken is meant to be kept in the memory of the calling
	// process and it must never be persisted by the caller.
	//
	// The daemon transparently renews the access token as long as renewing it
	// does not require the interaction of the user. If no usable credential can
	// be obtained without such an interaction, the RPC returns UNAUTHENTICATED
	// and the caller is supposed to start or to watch an Authenticate Operation
	// instead.
	GetAPICredential(context.Context, *GetAPICredentialRequest) (*GetAPICredentialResponse, error)
	// UpdateDomainSettings replaces the persisted local settings of a domain.
	//
	// Updating the settings does not reconfigure an already active Connection.
	// The new settings are used by the subsequent Connect Operations.
	UpdateDomainSettings(context.Context, *UpdateDomainSettingsRequest) (*DomainSettings, error)
	// DeleteDomain removes a domain entirely. The domain is disconnected and
	// logged out if needed and both its credentials and its persisted
	// DomainSettings are removed.
	DeleteDomain(context.Context, *DeleteDomainRequest) (*metav1.OperationResult, error)
	mustEmbedUnimplementedMainServiceServer()
}

// UnimplementedMainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMainServiceServer struct{}

func (UnimplementedMainServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedMainServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedMainServiceServer) WatchStatus(*WatchStatusRequest, grpc.ServerStreamingServer[GetStatusResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchStatus not implemented")
}
func (UnimplementedMainServiceServer) Authenticate(context.Context, *AuthenticateRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedMainServiceServer) Connect(context.Context, *ConnectRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedMainServiceServer) Disconnect(context.Context, *DisconnectRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedMainServiceServer) Logout(context.Context, *LogoutRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedMainServiceServer) GetOperation(context.Context, *GetOperationRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedMainServiceServer) CancelOperation(context.Context, *CancelOperationRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOperation not implemented")
}
func (UnimplementedMainServiceServer) GetAPICredential(context.Context, *GetAPICredentialRequest) (*GetAPICredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAPICredential not implemented")
}
func (UnimplementedMainServiceServer) UpdateDomainSettings(context.Context, *UpdateDomainSettingsRequest) (*DomainSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDomainSettings not implemented")
}
func (UnimplementedMainServiceServer) DeleteDomain(context.Context, *DeleteDomainRequest) (*metav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDomain not implemented")
}
func (UnimplementedMainServiceServer) mustEmbedUnimplementedMainServiceServer() {}
func (UnimplementedMainServiceServer) testEmbeddedByValue()                     {}

// UnsafeMainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MainServiceServer will
// result in compilation errors.
type UnsafeMainServiceServer interface {
	mustEmbedUnimplementedMainServiceServer()
}

func RegisterMainServiceServer(s grpc.ServiceRegistrar, srv MainServiceServer) {
	// If the following call pancis, it indicates UnimplementedMainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MainService_ServiceDesc, srv)
}

func _MainService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_WatchStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MainServiceServer).WatchStatus(m, &grpc.GenericServerStream[WatchStatusRequest, GetStatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MainService_WatchStatusServer = grpc.ServerStreamingServer[GetStatusResponse]

func _MainService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_CancelOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).CancelOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_CancelOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).CancelOperation(ctx, req.(*CancelOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetAPICredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAPICredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetAPICredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetAPICredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetAPICredential(ctx, req.(*GetAPICredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateDomainSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDomainSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateDomainSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateDomainSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateDomainSettings(ctx, req.(*UpdateDomainSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_DeleteDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).DeleteDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_DeleteDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).DeleteDomain(ctx, req.(*DeleteDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MainService_ServiceDesc is the grpc.ServiceDesc for MainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.client.daemon.v1.MainService",
	HandlerType: (*MainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _MainService_GetInfo_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _MainService_GetStatus_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _MainService_Authenticate_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _MainService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _MainService_Disconnect_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _MainService_Logout_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _MainService_GetOperation_Handler,
		},
		{
			MethodName: "CancelOperation",
			Handler:    _MainService_CancelOperation_Handler,
		},
		{
			MethodName: "GetAPICredential",
			Handler:    _MainService_GetAPICredential_Handler,
		},
		{
			MethodName: "UpdateDomainSettings",
			Handler:    _MainService_UpdateDomainSettings_Handler,
		},
		{
			MethodName: "DeleteDomain",
			Handler:    _MainService_DeleteDomain_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStatus",
			Handler:       _MainService_WatchStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "daemonv1.proto",
}
